### ISSUE TITLE
Uncaught exception 'RuntimeException' with message 'The provided account key '' is not a valid base64 string. It has to pass the check 'base64_decode(, true)'.'

### ISSUE THREAD

**Issue by ekoheryanto** [Azure-Samples/storage-blobs-php-quickstart#8]
Fatal error: Uncaught exception 'RuntimeException' with message 'The provided account key '' is not a valid base64 string. It has to pass the check 'base64_decode(, true)'.' in D:\home\site\wwwroot\vendor\microsoft\azure-storage-common\src\Common\Internal\StorageServiceSettings.php:112 Stack trace: #0 D:\home\site\wwwroot\vendor\microsoft\azure-storage-common\src\Common\Internal\ServiceSettings.php(133): MicrosoftAzure\Storage\Common\Internal\StorageServiceSettings::MicrosoftAzure\Storage\Common\Internal\{closure}('') #1 D:\home\site\wwwroot\vendor\microsoft\azure-storage-common\src\Common\Internal\ServiceSettings.php(273): MicrosoftAzure\Storage\Common\Internal\StorageServiceSettings::MicrosoftAzure\Storage\Common\Internal\{closure}(Array) #2 D:\home\site\wwwroot\vendor\microsoft\azure-storage-common\src\Common\Internal\StorageServiceSettings.php(401): MicrosoftAzure\Storage\Common\Internal\ServiceSettings::matchedSpecification(Array, Object(Closure), Object(Closure)) #3 D:\home\site\wwwroot\vendor\micr in D:\home\site\wwwroot\vendor\microsoft\azure-storage-common\src\Common\Internal\StorageServiceSettings.php on line 112

can I help this error message why the account_key is invalid with base64_decode

**Comment by samuelmamootil** [comment]
getting the same error

**Comment by isaaczai88** [comment]
same error here, any solution?

**Comment by natanmoraes** [comment]
The readme is outdated, you need to set the following environment variables:
`export ACCOUNT_NAME="<youraccountname>` and `export ACCOUNT_KEY="<youraccountkey>"`

**Comment by natanmoraes** [comment]
See #9
